export const SECTORS = [
    'All',
    'Agriculture & Farming',
    'Arts, Media & Entertainment',
    'Automotive & Mechanics',
    'Beauty & Personal Care',
    'Call Centers & BPO',
    'Carpentry & Woodwork',
    'Childcare & Early Childhood Development',
    'Construction & Engineering',
    'Customer Service',
    'Domestic & Cleaning Services',
    'Education & Training',
    'Electrical & Electronics',
    'Energy & Utilities',
    'Events & Conference Management',
    'Finance & Accounting',
    'Graphic Design & Creative Services',
    'Healthcare & Medical Services',
    'Hospitality & Tourism',
    'HVAC & Refrigeration',
    'Legal Services',
    'Manufacturing & Production',
    'Marketing & Communications',
    'Media & Journalism',
    'Mining & Resources',
    'Painting & Decorating',
    'Photography & Videography',
    'Plumbing & Pipefitting',
    'Public Administration',
    'Real Estate & Property',
    'Retail & Sales',
    'Security Services',
    'Social Services & NGO',
    'Sports & Fitness',
    'Technology & IT',
    'Telecommunications',
    'Transport & Logistics',
    'Warehouse & Storage',
    'Waste Management & Recycling',
    'Welding & Metalwork'
];

export const JOB_ROLES_BY_SECTOR: Record<string, string[]> = {
    'Technology & IT': [
        'All',
        'Software Developer',
        'Web Developer',
        'Mobile App Developer',
        'Data Scientist',
        'Data Analyst',
        'Database Administrator',
        'IT Support Technician',
        'Network Administrator',
        'System Administrator',
        'Cybersecurity Specialist',
        'DevOps Engineer',
        'Cloud Engineer',
        'UI/UX Designer',
        'QA Tester',
        'IT Project Manager',
        'Business Analyst'
    ],
    'Healthcare & Medical Services': [
        'All',
        'Doctor / Physician',
        'Specialist Doctor',
        'Surgeon',
        'General Practitioner (GP)',
        'Dentist',
        'Pharmacist',
        'Registered Nurse',
        'Enrolled Nurse',
        'Nursing Assistant',
        'Midwife',
        'Paramedic',
        'Emergency Medical Technician (EMT)',
        'Radiographer',
        'Physiotherapist',
        'Occupational Therapist',
        'Speech Therapist',
        'Psychologist',
        'Clinical Psychologist',
        'Counselor',
        'Medical Laboratory Technician',
        'Hospital Administrator',
        'Healthcare Manager'
    ],
    'Education & Training': [
        'All',
        'Teacher',
        'Primary School Teacher',
        'High School Teacher',
        'Subject Teacher (Math, Science, etc.)',
        'University Lecturer',
        'Professor',
        'Special Education Teacher',
        'Teaching Assistant',
        'Tutor',
        'Principal / Headmaster',
        'Education Administrator',
        'Curriculum Developer',
        'Education Consultant',
        'Training Facilitator',
        'Corporate Trainer'
    ],
    'Finance & Accounting': [
        'All',
        'Accountant',
        'Chartered Accountant (CA)',
        'Management Accountant',
        'Auditor',
        'Tax Consultant',
        'Financial Analyst',
        'Financial Manager',
        'Chief Financial Officer (CFO)',
        'Bookkeeper',
        'Payroll Administrator',
        'Financial Advisor',
        'Investment Analyst',
        'Risk Analyst',
        'Credit Analyst',
        'Budget Analyst',
        'Accounts Payable/Receivable Clerk'
    ],
    'Construction & Engineering': [
        'All',
        'Civil Engineer',
        'Structural Engineer',
        'Mechanical Engineer',
        'Electrical Engineer',
        'Chemical Engineer',
        'Industrial Engineer',
        'Construction Manager',
        'Project Manager',
        'Site Manager',
        'Quantity Surveyor',
        'Architect',
        'Building Inspector',
        'Construction Worker',
        'Foreman',
        'Surveyor',
        'Draughtsman',
        'Health & Safety Officer'
    ],
    'Hospitality & Tourism': [
        'All',
        'Chef',
        'Sous Chef',
        'Cook',
        'Waiter / Waitress',
        'Bartender',
        'Barista',
        'Restaurant Manager',
        'Kitchen Manager',
        'Hotel Manager',
        'Front Desk Receptionist',
        'Concierge',
        'Housekeeper',
        'Room Attendant',
        'Tour Guide',
        'Travel Agent',
        'Event Coordinator',
        'Catering Manager'
    ],
    'Transport & Logistics': [
        'All',
        'Truck Driver (Code 14)',
        'Delivery Driver (Code 10)',
        'Taxi Driver',
        'Uber/Bolt Driver',
        'Bus Driver',
        'Forklift Operator',
        'Logistics Coordinator',
        'Supply Chain Manager',
        'Warehouse Manager',
        'Dispatcher',
        'Fleet Manager',
        'Courier',
        'Freight Handler',
        'Shipping Clerk'
    ],
    'Retail & Sales': [
        'All',
        'Sales Assistant',
        'Cashier',
        'Store Manager',
        'Assistant Manager',
        'Merchandiser',
        'Stock Controller',
        'Sales Representative',
        'Sales Manager',
        'Account Manager',
        'Business Development Manager',
        'Retail Buyer',
        'Visual Merchandiser',
        'Customer Service Representative'
    ],
    'Security Services': [
        'All',
        'Security Officer / Guard',
        'Armed Response Officer',
        'Security Supervisor',
        'Security Manager',
        'CCTV Operator',
        'Access Control Officer',
        'Loss Prevention Officer',
        'Bodyguard / Close Protection Officer',
        'Security Consultant',
        'Security Trainer'
    ],
    'Electrical & Electronics': [
        'All',
        'Electrician',
        'Industrial Electrician',
        'Electrical Engineer',
        'Electrical Technician',
        'Electronics Technician',
        'Instrumentation Technician',
        'Solar Installer',
        'Electrical Inspector',
        'Maintenance Electrician'
    ],
    'Plumbing & Pipefitting': [
        'All',
        'Plumber',
        'Industrial Plumber',
        'Pipefitter',
        'Gasfitter',
        'Drainage Specialist',
        'Plumbing Supervisor',
        'Plumbing Inspector'
    ],
    'Welding & Metalwork': [
        'All',
        'Welder',
        'TIG Welder',
        'MIG Welder',
        'Arc Welder',
        'Boilermaker',
        'Metal Fabricator',
        'Sheet Metal Worker',
        'Welding Inspector',
        'Welding Supervisor'
    ],
    'Marketing & Communications': [
        'All',
        'Marketing Manager',
        'Marketing Coordinator',
        'Digital Marketing Specialist',
        'Social Media Manager',
        'Content Creator',
        'Copywriter',
        'SEO Specialist',
        'Brand Manager',
        'Public Relations Officer',
        'Communications Manager',
        'Advertising Executive',
        'Market Researcher'
    ],
    'Legal Services': [
        'All',
        'Lawyer / Attorney',
        'Advocate',
        'Legal Advisor',
        'Corporate Lawyer',
        'Prosecutor',
        'Paralegal',
        'Legal Secretary',
        'Compliance Officer',
        'Contract Manager'
    ]
};
